# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Laura's Code
email: 87a22066@opayq.com
description: Because my memory sucks.
#baseurl: "/portfolio" # the subpath of your site, e.g. /blog
#url: "https://lrobeson.github.io" # the base hostname & protocol for your site
twitter_username: codeslikeagirl
github_username:  lrobeson
paginate: 5

# Build settings
markdown: kramdown
permalink: :title/

gems: [jekyll-paginate]
